### PR TITLE
Feature/different url generation

### PR DESCRIPTION
**Pull request by AlviseSembenico**

### CODE REVIEW

**Comment by alextreme** [comment]
@AlviseSembenico please expand this with a test

**Comment by alextreme** [comment]
@AlviseSembenico and check Jenkins:

Screenshot_2019-04-18_13-10-48

**Comment by AlviseSembenico** [comment]
@alextreme tests have been added, I still do not find the right PR in jenkins though.

**Comment by alextreme** [comment]
As requested in the issue I'd like to talk this through first to ensure we solve Henri's request.

**Pull request merged**
