### PR TITLE
:bug: fix slash

### PR DESCRIPTION
**Pull request by AlviseSembenico**

### CODE REVIEW

**Comment by alextreme** [comment]
@AlviseSembenico could you write a regressiontest for this?

**Comment by AlviseSembenico** [comment]
That's hard because it needed a hosted docker. I can write ad hoc function test that tests specifically that particular function.

**Comment by alextreme** [comment]
Testing only sub_url_request and sub_url_response is sufficient for me.

**Comment by AlviseSembenico** [comment]
Work in progress

**Comment by AlviseSembenico** [comment]
@alextreme tests added

**Comment by alextreme** [comment]
Looks good, thanks!

**Comment by alextreme** [comment]
@AlviseSembenico check the 2 failures on jenkins:

http://jenkins.maykin.nl/job/VNG%20Github/job/api-testvoorziening/view/change-requests/job/PR-123/2/

**Comment by AlviseSembenico** [comment]
@AlviseSembenico Those failures has been fixed in the other branch.

**Pull request merged**
