### PR TITLE
Feature/badge improvement

### PR DESCRIPTION
**Pull request by AlviseSembenico**
I know it is a big PR but  everything was wired to it would be difficoult to split it up.

### CODE REVIEW

**Comment by alextreme** [comment]
@AlviseSembenico I noticed that you're keeping both the 'id' and 'uuid' views accessible for your server run.

I'd suggest we switch to only the uuid-one. There's not really a reason to have two different URL patterns to access the same view.

**Comment by alextreme** [comment]
Besides that I'd suggest to expand your tests with the additional badge/server-run details. You're introducing useful stuff that deserves to be tested properly :)

**Comment by AlviseSembenico** [comment]
@alextreme New tests added

**Comment by alextreme** [comment]
http://jenkins.maykin.nl/job/VNG%20Github/job/api-testvoorziening/view/change-requests/job/PR-144/

**Comment by AlviseSembenico** [comment]
The two errors are fixed in https://github.com/VNG-Realisatie/api-testvoorziening/pull/145/commits/de525da12b8e14c918e4648eeefc7e1de43009ad

**Pull request merged**
