### PR TITLE
Feature/#343 badge snippet

### PR DESCRIPTION
**Pull request by AlviseSembenico**

### CODE REVIEW

**Comment by alextreme** [comment]
@AlviseSembenico can add this JS dependancy to the project? I'd like this not to be dependant on some CDN JS master-branch.

**Comment by AlviseSembenico** [comment]
Is in the package.json fine or somewhere else?

**Comment by alextreme** [comment]
> Is in the package.json fine or somewhere else?

package.json is fine, or you can add it to your src/vng/static/js directory and it should become available via /static/js/

**Comment by AlviseSembenico** [comment]
@alextreme moved the dependency to the package json file, can you please confirm me if it is enough?

**Comment by alextreme** [comment]
@AlviseSembenico this doesn't work for me, please check with npm install && gulp build locally.

As mentioned it's fine to keep such small JS dependancies outside of package.json in the static directory.

**Comment by AlviseSembenico** [comment]
@alextreme put the file locally in the static

**Pull request merged**
