### PR TITLE
:bug: fix save issue multiple servers

### PR DESCRIPTION
**Pull request by AlviseSembenico**

### CODE REVIEW

**Comment by alextreme** [comment]
@AlviseSembenico could you add a regressiontest for this?

**Comment by AlviseSembenico** [comment]
@alextreme done!

**Comment by alextreme** [comment]
@AlviseSembenico  :thisisfine: http://jenkins.maykin.nl/job/VNG%20Github/job/api-testvoorziening/view/change-requests/job/PR-125/2/

**Comment by AlviseSembenico** [comment]
I don't have access to jenkis remotely so as I will be in the office I will check it out.

**Comment by alextreme** [comment]
> I don't have access to jenkis remotely so as I will be in the office I will check it out.

See the details on remote Jenkins access in our Slack

**Comment by AlviseSembenico** [comment]
@alextreme Fixed

**Pull request merged**
