### PR TITLE
Feature/core ui

### PR DESCRIPTION
**Pull request by AlviseSembenico**
Huge PR but not logic involved.

### CODE REVIEW

**Comment by AlviseSembenico** [comment]
I am deploying it on test

**Comment by AlviseSembenico** [comment]
@alextreme It seems that everything works out, you can check it out in https://vng-test.maykin.nl/

**Comment by AlviseSembenico** [comment]
@AlviseSembenico I fixed what you pointed out, now i deploy on test

**Comment by alextreme** [comment]
@AlviseSembenico seems there are still 12 tests failing:
http://jenkins.maykin.nl/job/VNG Github/job/api-testvoorziening/view/change-requests/job/PR-149/

**Comment by AlviseSembenico** [comment]
It is good since the forms have been moved. As I finish to improve the pdf i fix the tests

**Comment by AlviseSembenico** [comment]
@alextreme Tests fixed.

**Comment by alextreme** [comment]
Cool!

**Pull request merged**
