### PR TITLE
Test for body rewrite subdomain

### PR DESCRIPTION
**Pull request by AlviseSembenico**

### CODE REVIEW

**Comment by alextreme** [comment]
@AlviseSembenico FYI:

Screenshot_2019-04-17_15-13-01

**Comment by AlviseSembenico** [comment]
My bad, I dropped a logging, restored

**Comment by alextreme** [comment]
@AlviseSembenico from Jenkins (I've started a rebuild):

npm ERR! file /tmp/jenkins-slave/workspace/ithub_api-testvoorziening_PR-133/package.json
npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token } in JSON at position 2164 while parsing near '...rgs": "^9.0.1",
npm ERR! JSON.parse     }
npm ERR! JSON.parse }
npm ERR! JSON.parse '
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

**Comment by AlviseSembenico** [comment]
@alextreme fixed, forgot to delete a coma in the json file, why isn't it flexible like python dict?

**Comment by alextreme** [comment]
Thanks! Yes everything that starts with JS is a PITA

**Pull request merged**
